# Site settings
title: iBlog Efstathios Iosifidis
description: iBlog Efstathios Iosifidis on github
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iosifidis.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Efstathios Iosifidis
user_description: openSUSE member, GNOME Foundation member
user_title: iBlog
email: iefstathios@gmail.com
twitter_username: eiosifidis
github_username:  iosifidis
gplus_username:  +EfstathiosIosifidis
disqus_username: efstathiosiosifidis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
