# Site settings
title: Τα εγχειρίδιά μου
description: Διάφορα εγχειρίδια για Nextcloud, openSUSE, ONLYOFFICE, ownCloud, GNU Health
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iosifidis.github.io" # the base hostname & protocol for your site e.g. http://iosifidis.gr

# User settings
username: Ευστάθιος Ιωσηφίδης
user_description: Veterinarian, openSUSE member, GNOME Foundation member
user_title: Εγχειρίδια για Nextcloud, openSUSE, GNU Health, ONLYOFFICE, ownCloud και άλλα πολλά!!!
email: iefstathios@gmail.com
linkedin_username: eiosifidis
facebook_username: eiosifidis
instagram_username: e.iosifidis
twitter_username: eiosifidis
github_username:  iosifidis
disqus_username: iblog-eiosifidis

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Αρχική
    url: /
  - title: Σειρές
    url: /series
  - title: Ετικέτες
    url: /tags
  - title: Περί
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
